name: duck
channels:
- conda-forge
- pytorch
dependencies:
- pip
- python>=3.7,<3.10
- pywps>=4.5.1,<4.6
- jinja2
- click
- psutil
# tests
- pytest
# clint ai
- pytorch>=1.8.0
- tqdm>=4.59.0
- torchvision>=0.2.1
- numpy>=1.20.1
- matplotlib>=3.4.3
- tensorboardX>=2.4.0
- xarray>=0.20.2
- netcdf4>=1.5.8
